/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author Pedro
 */
public class JDialogEndereco extends javax.swing.JDialog {

    /** Creates new form JDialogEndereco */
    static String ip;
    static int porta;
    public JDialogEndereco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jTxtIP = new javax.swing.JTextField();
        jBtnOK = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jTxtPorta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dados do Servidor");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/IMG/ic_launcher-web.png")));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jTxtIP.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jTxtIP.setForeground(new java.awt.Color(153, 153, 153));
        jTxtIP.setText("Endereço IP do Servidor");
        jTxtIP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jTxtIP.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTxtIPMouseClicked(evt);
            }
        });
        jTxtIP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTxtIPActionPerformed(evt);
            }
        });
        jTxtIP.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtIPFocusLost(evt);
            }
        });
        jTxtIP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTxtIPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTxtIPKeyTyped(evt);
            }
        });

        jBtnOK.setBackground(new java.awt.Color(255, 255, 255));
        jBtnOK.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jBtnOK.setText("OK");
        jBtnOK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnOKActionPerformed(evt);
            }
        });

        jBtnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jBtnCancelar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jTxtPorta.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jTxtPorta.setForeground(new java.awt.Color(153, 153, 153));
        jTxtPorta.setText("Nº Porta do Servidor");
        jTxtPorta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jTxtPorta.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTxtPortaMouseClicked(evt);
            }
        });
        jTxtPorta.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtPortaFocusLost(evt);
            }
        });
        jTxtPorta.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTxtPortaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTxtPortaKeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 181, 229));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clara");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jBtnOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jBtnCancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 166, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 4, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTxtPorta)
                    .add(jTxtIP))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(7, 7, 7)
                .add(jTxtIP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jTxtPorta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jBtnCancelar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jBtnOK, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static String getIP()
    {
        return ip;
    }                                
    public static int getPorta()
    {
        return porta;
    }
    private void jBtnOKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnOKActionPerformed
    {//GEN-HEADEREND:event_jBtnOKActionPerformed
        // TODO add your handling code here:
        int quantos = 0;
        if(!jTxtIP.getText().isEmpty() && !jTxtPorta.getText().isEmpty())
        {
            ip = jTxtIP.getText();
            for(int i = 0; i < ip.length(); i++)
            {
                if(ip.charAt(i) == '.')
                {
                    quantos++;
                }
            }
            if(quantos == 3)
            { 
                porta = Integer.parseInt(jTxtPorta.getText());
                setVisible(false);
            }
        }
    }//GEN-LAST:event_jBtnOKActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnCancelarActionPerformed
    {//GEN-HEADEREND:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTxtPortaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTxtPortaKeyPressed
    {//GEN-HEADEREND:event_jTxtPortaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jBtnOKActionPerformed(null);
        }

    }//GEN-LAST:event_jTxtPortaKeyPressed

    private void jTxtIPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTxtIPKeyTyped
    {//GEN-HEADEREND:event_jTxtIPKeyTyped
        // TODO add your handling code here:
        String caractere = Character.toString(evt.getKeyChar());
        if(caractere.matches("[a-zA-Z]"))
        {
            evt.consume();
        }
        if(firstClick)
        {
            jTxtIP.setText("");
            jTxtIP.setForeground(Color.BLACK);
            jTxtIP.setFont(new java.awt.Font("Segoe UI", 0, 16));
            firstClick = false;
        }
    }//GEN-LAST:event_jTxtIPKeyTyped

    private void jTxtPortaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTxtPortaKeyTyped
    {//GEN-HEADEREND:event_jTxtPortaKeyTyped
        // TODO add your handling code here:
        String caractere = Character.toString(evt.getKeyChar());
        if(!caractere.matches("[0-9]"))
        {
            evt.consume();
        }
        if(firstClick2)
        {
            jTxtPorta.setText("");
            jTxtPorta.setForeground(Color.BLACK);
            jTxtPorta.setFont(new java.awt.Font("Segoe UI", 0, 16));
            firstClick2 = false;
        }
        
    }//GEN-LAST:event_jTxtPortaKeyTyped
    
    private void jTxtIPKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTxtIPKeyPressed
    {//GEN-HEADEREND:event_jTxtIPKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jTxtPorta.requestFocusInWindow();
        }
    }//GEN-LAST:event_jTxtIPKeyPressed

    private void jTxtIPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTxtIPActionPerformed
    {//GEN-HEADEREND:event_jTxtIPActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTxtIPActionPerformed
    boolean firstClick = true, firstClick2 = true;
    private void jTxtIPMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTxtIPMouseClicked
    {//GEN-HEADEREND:event_jTxtIPMouseClicked
        // TODO add your handling code here:
        if(firstClick)
        {
            jTxtIP.setText("");
            jTxtIP.setForeground(Color.BLACK);
            jTxtIP.setFont(new java.awt.Font("Segoe UI", 0, 16));
            firstClick = false;
        }
    }//GEN-LAST:event_jTxtIPMouseClicked

    private void jTxtPortaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTxtPortaMouseClicked
    {//GEN-HEADEREND:event_jTxtPortaMouseClicked
        // TODO add your handling code here:
        if(firstClick2)
        {
            jTxtPorta.setText("");
            jTxtPorta.setForeground(Color.BLACK);
            jTxtPorta.setFont(new java.awt.Font("Segoe UI", 0, 16));
            firstClick2 = false;
        }
        
    }//GEN-LAST:event_jTxtPortaMouseClicked

    private void jTxtIPFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtIPFocusLost
    {//GEN-HEADEREND:event_jTxtIPFocusLost
        // TODO add your handling code here:
        if(jTxtIP.getText().equals(""))
        {
            jTxtIP.setText("Endereço IP do Servidor");
            jTxtIP.setForeground(new Color(153, 153, 153));
            jTxtIP.setFont(new java.awt.Font("Segoe UI Light", 1, 18));
            firstClick = true;
        }
    }//GEN-LAST:event_jTxtIPFocusLost

    private void jTxtPortaFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtPortaFocusLost
    {//GEN-HEADEREND:event_jTxtPortaFocusLost
        // TODO add your handling code here:
        if(jTxtPorta.getText().equals(""))
        {
            jTxtPorta.setText("Nº Porta do Servidor");
            jTxtPorta.setForeground(new Color(153, 153, 153));
            jTxtPorta.setFont(new java.awt.Font("Segoe UI Light", 1, 18));
            firstClick2 = true;
        }
    }//GEN-LAST:event_jTxtPortaFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTxtIP;
    private javax.swing.JTextField jTxtPorta;
    // End of variables declaration//GEN-END:variables

}
