package Interface;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.Box;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class JFrmCliente extends javax.swing.JFrame
{

    /**
     * Creates new form NewJFrame
     */
    private BufferedReader entrada;
    private PrintWriter saida;
    private String nome;
    private int pX, pY;
    private DefaultListModel dlm;
    private Color cor;
    private final Color cor2 = new Color(238,238,252);
    Map<Integer, Boolean>teclas = new HashMap<>(); 
    private String ip;
    private int porta = 0;
    private boolean continua = true;
    Socket socket;
    String versos[] =  {"Hello", "Is there anybody in there?",
                        "Just nod if you can hear me",
                        "Is there anyone at home?", 
                        "Come on now", "I hear you're feeling down",
                        "Well, I can ease your pain",
                        "And get you on your feet again"};
    public JFrmCliente()
    {
        initComponents();
        teclas.put(KeyEvent.VK_ENTER, false);
        teclas.put(KeyEvent.VK_SHIFT, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        listMessages = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clara - Cliente");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/IMG/ic_launcher-web.png")));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(22, 73, 154));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                jPanel1MouseDragged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jPanel4, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(1);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jTextArea2.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTextArea2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTextArea2KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea2);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listMessages.setBackground(new java.awt.Color(255, 255, 255));
        listMessages.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        listMessages.setMaximumSize(new java.awt.Dimension(0, 0));
        listMessages.setMinimumSize(new java.awt.Dimension(0, 0));
        listMessages.setName(""); // NOI18N
        listMessages.setLayout(new javax.swing.BoxLayout(listMessages, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane4.setViewportView(listMessages);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jPanel5, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jScrollPane4, org.jdesktop.beansbinding.ELProperty.create("${border}"), jPanel5, org.jdesktop.beansbinding.BeanProperty.create("border"));
        bindingGroup.addBinding(binding);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Pessoas na sala:");

        jScrollPane3.setBorder(null);

        jList1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jList1.setModel(new DefaultListModel());
        jList1.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane3.setViewportView(jList1);

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("x");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>Nerd for Speed 2111,86 - Cliente - Clara</html>");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("c");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel1)
                .addComponent(jLabel5)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel1MouseClicked
    {//GEN-HEADEREND:event_jLabel1MouseClicked
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?",
                  "Am i... ginger?", JOptionPane.YES_NO_OPTION);
        if(resp == 0)
        {
            try
            {
                saida.println("@<out_user>");
                continua = false;
                notConnect = false;
                dispose();
                socket.close();
            }catch(IOException e)
            {
                e.printStackTrace();
            }
            finally
            {
                continua = false;
                notConnect = false;
                dispose();
            }
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jTextArea2KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextArea2KeyPressed
    {//GEN-HEADEREND:event_jTextArea2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_SHIFT)
            teclas.put(evt.getKeyCode(), true);
        if(teclas.get(KeyEvent.VK_ENTER) && teclas.get(KeyEvent.VK_SHIFT))
        {
            jTextArea2.append("\n");
        }
        else if((evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER))
        {
            if(!jTextArea2.getText().isEmpty())
            {
                evt.consume();
                saida.println(formatar(jTextArea2.getText(), false));
                //addBubble("Eu", formatar(jTextArea2.getText(), false), new Color(105, 105, 205));
                jTextArea2.setText("");
            }
            else
            {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jTextArea2KeyPressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel1MousePressed
    {//GEN-HEADEREND:event_jPanel1MousePressed
        // TODO add your handling code here:
        pX=evt.getX();
        pY=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel1MouseDragged
    {//GEN-HEADEREND:event_jPanel1MouseDragged
        // TODO add your handling code here:
        setLocation(getLocation().x+evt.getX()-pX,getLocation().y+evt.getY()-pY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel5MouseClicked
    {//GEN-HEADEREND:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel2MouseClicked
    {//GEN-HEADEREND:event_jLabel2MouseClicked
        // TODO add your handling code here:
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextArea2KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextArea2KeyReleased
    {//GEN-HEADEREND:event_jTextArea2KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_SHIFT)
            teclas.put(evt.getKeyCode(), false);
    }//GEN-LAST:event_jTextArea2KeyReleased
    private void getEnderecoServidor() 
    {
        JDialogEndereco end = new JDialogEndereco(this, true);
        end.setVisible(true);
        ip = end.getIP();
        porta = end.getPorta();
        if(ip == null || porta == 0)
        {
            dispose();
        }
        else
        {
            if(ip.isEmpty())
                dispose();
        }
    }
    private String getNome()
    {
        JDialogNome c = new JDialogNome(this, true);
        c.setVisible(true);
        nome = formatar(c.getNome(), true);
        cor = c.getColor();
        jList1.setSelectionBackground(cor);
        return nome;
    }
    int cont = 0;
    boolean notConnect = true;
    private Thread crono()
    {
        return new Thread()
        {
            @Override
            public void run()
            {
                while(notConnect && cont <= 20)
                {
                    try
                    {
                        sleep(1000);
                        listMessages.removeAll();
                        listMessages.revalidate();
                    } catch (InterruptedException ex)
                    {
                        ex.printStackTrace();
                    }
                    addBubble("~Clara", (cont++)+"/20 segundos restantes.", cor2);
                }
            }
        };
    }
    public Thread loop()
    {
        Thread a = new Thread()
        {
            @Override
            public void run()
            {
                try 
                {
                    getEnderecoServidor();
                    crono().start();
                    socket = new Socket(ip, porta);
                    notConnect = false;
                    entrada = new BufferedReader(new InputStreamReader( socket.getInputStream(), StandardCharsets.UTF_8));
    		    saida = new PrintWriter(new OutputStreamWriter(socket.getOutputStream(), StandardCharsets.UTF_8), true);
                    while(continua)
                    {
                        String line = entrada.readLine();
                        if(line.startsWith("enter_username:"))
                        {
                            saida.println(getNome());
                        }
                        else if(line.startsWith("accept_username:"))
                        {
                            jTextArea2.setEditable(true);
                        }
                        else if(line.startsWith("send_message:"))
                        {
                            List<String> l = parseList(line.substring(13), false);
                            if(l.get(0).equals(nome))
                            {
                                l.set(0, "Eu");
                                addBubble(l.get(0), l.get(1), cor);
                            }
                            else
                            {
                                addBubble(l.get(0), l.get(1), cor2);
                            }
                        }
                        else if(line.startsWith("new_user:"))
                        {
                            DefaultListModel dlm2 = new DefaultListModel();
                            List<String> nomesLogadosList = parseList(line.substring(9), true);
                            String last = nomesLogadosList.get(nomesLogadosList.size() - 1);
                            addBubble("~Clara", desformatar(last)+" entrou na sala.", cor2);
                            nomesLogadosList.remove(nome);
                            dlm2.addElement("Você");
                            for(String a : nomesLogadosList)
                            {
                                dlm2.addElement(desformatar(a)); 
                            }
                            jList1.setModel(dlm2);
                        }
                        else if(line.startsWith("nome_sala:"))
                        {
                            jLabel3.setText(line.substring(10)+" - Cliente - Clara");
                        }
                        else if(line.startsWith("out_user:"))
                        {
                            DefaultListModel dlm2 = (DefaultListModel) jList1.getModel();
                            dlm2.removeElement(desformatar(line.substring(9)));
                            jList1.setModel(dlm2);
                            addBubble("~Clara",desformatar(line.substring(9))+" saiu da sala.", cor2);
                        }
                    }
                }catch (IOException ex)
                {
                    notConnect = false;
                    ex.printStackTrace();
                    addBubble("~Clara", desformatar("Look my hor... Quero dizer, ocorreu um problema:\n"+ex.getMessage()),
                    cor2);
                }
            }
        };
        return a;
    }
    private List<String> parseList(String a, boolean space)
    {
        String regex = (space) ? "\\[|\\]| " : "\\[|\\]|";
        String stringList = a.replaceAll(regex, "").replaceFirst(" ", "");
        List<String> list = new ArrayList<>(Arrays.asList(stringList.split(",")));
        return list;
    }
    private String formatar(String texto, boolean space)
    {
        texto = texto.replaceAll("\n", "@<newLine/>");
        texto = texto.replaceAll("\\[", "@<conchelte1/>").replaceAll("\\]", "@<conchelte2/>");
        texto = texto.replaceAll(",", "@<virgula/>");
        texto = space ? texto.replaceAll(" ", "@<space/>") : texto;//Quando espaços são inseridos no nome isso da pau
        return texto;
    }
    private String desformatar(String texto)
    {
        //texto = texto.replaceAll("@<newLine/>", "\n");
        texto = texto.replaceAll("@<conchelte1/>", "\\[").replaceAll("@<conchelte2/>", "\\]");
        texto = texto.replaceAll("@<virgula/>", ",");
        texto = texto.replaceAll("@<space/>"," ");//Quando espaços são inseridos no nome isso da pau
        return texto;
    }
    private void addBubble(String nome, String menssagem, Color c)
    {
        Bubble.Bubble b = new Bubble.Bubble(desformatar(nome), desformatar(menssagem));
        b.setAlignmentX(LEFT_ALIGNMENT);
        b.setBackground(c);
        listMessages.add(b);
        listMessages.add(Box.createRigidArea(new Dimension(0, 5)));
        int height = (int)listMessages.getPreferredSize().getHeight();
        listMessages.revalidate();
        Rectangle rect = new Rectangle(0, height,10,10);
        listMessages.scrollRectToVisible(rect);
    }
    public void princi()
    {
        JFrmCliente c = new JFrmCliente();
        c.setVisible(true);
        c.loop().start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel listMessages;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
