/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Bubble;

import java.awt.Component;
import java.awt.Dimension;

/**
 *
 * @author Pedro
 */
public class Bubble extends javax.swing.JPanel
{

    /**
     * Creates new form NewJPanel
     * @param nome quem enviou a menssagem
     * @param menssagem conteudo da menssagem
     */
    public Bubble(String nome, String menssagem)
    {
        initComponents();
        Dimension d = new BubbleSize().getDimenssao(nome, menssagem);
        setMaximumSize(d);
        setPreferredSize(d);
        jLblName.setText(nome);
        jTxtAreaMessage.append(menssagem.replaceAll("@<newLine/>", "\n"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLblName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaMessage = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8));
        setAlignmentX(Component.LEFT_ALIGNMENT);
        setFocusTraversalPolicyProvider(true);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTxtAreaMessage, org.jdesktop.beansbinding.ELProperty.create("${background}"), this, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        setLayout(new java.awt.BorderLayout());

        jLblName.setText("<name>The Doctor</name>");
        add(jLblName, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTxtAreaMessage.setEditable(false);
        jTxtAreaMessage.setBackground(new java.awt.Color(238, 238, 252));
        jTxtAreaMessage.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTxtAreaMessage.setLineWrap(true);
        jScrollPane1.setViewportView(jTxtAreaMessage);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtAreaMessage;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    
    
}

